apiVersion: v1
kind: Service
metadata:
  name: portainer-external
  namespace: portainer
  labels:
    io.portainer.kubernetes.application.stack: portainer
    app.kubernetes.io/name: portainer
    app.kubernetes.io/instance: portainer
    app.kubernetes.io/version: "ce-latest-ee-2.12.2"
spec:
  selector:
    app.kubernetes.io/name: portainer
    app.kubernetes.io/instance: portainer
  ports:
    - name: http
      port: 9000
      targetPort: 9000
      protocol: TCP
    - name: https
      port: 9443
      targetPort: 9443
      protocol: TCP
    - name: tcp-edge
      port: 8000
      targetPort: 8000
      protocol: TCP
  type: LoadBalancer
